name: Verify Black Hole Canister V1
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  verify:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aviate-labs/setup-dfx@v0.2.5
        with:
          dfx-version: 0.13.1
          install-moc: true
          vessel-version: 0.6.5
      - run: cd blackholes/v1 && npm run verify-blackhole 
