name: Verify Black Hole Canister V1
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  verify:
    runs-on: macos-latest
    steps:
      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: 0.13.1
      - name: Install vessel
        uses: ByronBecker/setup-dfx@v0.1.0
        with:
          vessel-version: 0.6.5
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: cd blackholes/v1 && npm run verify-blackhole 
